-- Report Card V2, Phase 1: academic setup (which exams make up a card), the school's report-card
-- design, a school-level co-scholastic activity list, and remarks / co-scholastic grades keyed by
-- setup + student. Purely additive: the Phase 0 report-card tables (assessment_group*,
-- report_card_template*, report_card_remark, co_scholastic_entry, report_card_publication) are
-- left untouched and keep serving the existing report cards.

-- ── Setup: one named card per school / academic session / class ─────────────────────────────
CREATE TABLE report_card_setup (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           BIGINT       NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    academic_session_id BIGINT       NOT NULL REFERENCES academic_session(id) ON DELETE RESTRICT,
    class_id            BIGINT       NOT NULL REFERENCES school_class(id) ON DELETE RESTRICT,
    name                VARCHAR(100) NOT NULL,
    result_mode         VARCHAR(20)  NOT NULL DEFAULT 'TOTAL',
    display_order       INTEGER      NOT NULL DEFAULT 0,
    created_by          VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_report_card_setup_result_mode CHECK (result_mode IN ('TOTAL', 'WEIGHTED')),
    CONSTRAINT ck_report_card_setup_name CHECK (length(btrim(name)) > 0)
);
-- Card names are unique per school / session / class, ignoring case and surrounding spaces.
CREATE UNIQUE INDEX uq_report_card_setup_school_session_class_name
    ON report_card_setup (school_id, academic_session_id, class_id, lower(btrim(name)));
CREATE INDEX idx_report_card_setup_school_session_class
    ON report_card_setup (school_id, academic_session_id, class_id);

-- ── Optional grouping of a setup's exams (Term 1 / Term 2) ─────────────────────────────────
CREATE TABLE report_card_setup_term (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     BIGINT        NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    setup_id      BIGINT        NOT NULL REFERENCES report_card_setup(id) ON DELETE CASCADE,
    name          VARCHAR(60)   NOT NULL,
    display_order INTEGER       NOT NULL DEFAULT 0,
    -- Fraction of the final result (0.5000 = 50%); only used by WEIGHTED setups.
    weight        NUMERIC(7, 4),
    CONSTRAINT ck_report_card_setup_term_weight CHECK (weight IS NULL OR (weight > 0 AND weight <= 1))
);
CREATE UNIQUE INDEX uq_report_card_setup_term_setup_name
    ON report_card_setup_term (setup_id, lower(btrim(name)));
CREATE INDEX idx_report_card_setup_term_setup ON report_card_setup_term (setup_id);

-- ── The exams a setup is made of (existing Results Phase 1 exams; never copied) ─────────────
CREATE TABLE report_card_setup_exam (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id      BIGINT        NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    setup_id       BIGINT        NOT NULL REFERENCES report_card_setup(id) ON DELETE CASCADE,
    -- RESTRICT: an exam used by a report card cannot disappear underneath it.
    exam_config_id BIGINT        NOT NULL REFERENCES exam_config(id) ON DELETE RESTRICT,
    term_id        BIGINT        REFERENCES report_card_setup_term(id) ON DELETE SET NULL,
    -- Fraction within its term (or of the final result without terms); WEIGHTED setups only.
    weight         NUMERIC(7, 4),
    display_order  INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT uq_report_card_setup_exam_setup_exam UNIQUE (setup_id, exam_config_id),
    CONSTRAINT ck_report_card_setup_exam_weight CHECK (weight IS NULL OR (weight > 0 AND weight <= 1))
);
CREATE INDEX idx_report_card_setup_exam_setup ON report_card_setup_exam (setup_id);
CREATE INDEX idx_report_card_setup_exam_exam ON report_card_setup_exam (exam_config_id);

-- A setup's exams must belong to the setup's own school, academic session and class. The service
-- validates this with clear messages; this trigger is the last line of defence.
CREATE OR REPLACE FUNCTION report_card_setup_exam_scope_check() RETURNS trigger AS $$
DECLARE
    s_school  BIGINT;
    s_session VARCHAR;
    s_class   BIGINT;
    s_class_n VARCHAR;
    e_school  BIGINT;
    e_session VARCHAR;
    e_class   BIGINT;
    e_class_n VARCHAR;
BEGIN
    SELECT su.school_id, a.label, su.class_id, c.name
      INTO s_school, s_session, s_class, s_class_n
      FROM report_card_setup su
      JOIN academic_session a ON a.id = su.academic_session_id
      JOIN school_class c ON c.id = su.class_id
     WHERE su.id = NEW.setup_id;
    SELECT school_id, session, class_id, class_name
      INTO e_school, e_session, e_class, e_class_n
      FROM exam_config WHERE id = NEW.exam_config_id;
    IF NEW.school_id <> s_school OR e_school IS DISTINCT FROM s_school
       OR e_session IS DISTINCT FROM s_session
       OR (e_class IS NOT NULL AND e_class <> s_class)
       OR (e_class IS NULL AND e_class_n IS DISTINCT FROM s_class_n) THEN
        RAISE EXCEPTION 'Exam % does not belong to the school, session and class of report card setup %',
            NEW.exam_config_id, NEW.setup_id USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.term_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM report_card_setup_term t WHERE t.id = NEW.term_id AND t.setup_id = NEW.setup_id) THEN
        RAISE EXCEPTION 'Term % is not part of report card setup %', NEW.term_id, NEW.setup_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_report_card_setup_exam_scope
    BEFORE INSERT OR UPDATE ON report_card_setup_exam
    FOR EACH ROW EXECUTE FUNCTION report_card_setup_exam_scope_check();

-- ── School-level design (one row per school; academic structure lives in the setup) ────────
CREATE TABLE school_report_card_design (
    school_id                 BIGINT       PRIMARY KEY REFERENCES school(id) ON DELETE RESTRICT,
    motto                     VARCHAR(150),
    footer_text               VARCHAR(300),
    watermark_mode            VARCHAR(10)  NOT NULL DEFAULT 'NONE',
    watermark_text            VARCHAR(40),
    show_photo                BOOLEAN      NOT NULL DEFAULT TRUE,
    show_qr                   BOOLEAN      NOT NULL DEFAULT TRUE,
    show_attendance           BOOLEAN      NOT NULL DEFAULT TRUE,
    show_co_scholastic        BOOLEAN      NOT NULL DEFAULT TRUE,
    show_teacher_remark       BOOLEAN      NOT NULL DEFAULT TRUE,
    show_principal_remark     BOOLEAN      NOT NULL DEFAULT TRUE,
    show_rank                 BOOLEAN      NOT NULL DEFAULT TRUE,
    show_promotion            BOOLEAN      NOT NULL DEFAULT FALSE,
    teacher_signature_label   VARCHAR(60)  NOT NULL DEFAULT 'Class Teacher',
    principal_signature_label VARCHAR(60)  NOT NULL DEFAULT 'Principal',
    updated_by                VARCHAR(255),
    updated_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision                  BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_school_report_card_design_watermark CHECK (watermark_mode IN ('NONE', 'TEXT', 'LOGO'))
);

-- ── Co-scholastic activities: configured once per school, not per card ─────────────────────
CREATE TABLE school_co_scholastic_activity (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id     BIGINT      NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    name          VARCHAR(80) NOT NULL,
    display_order INTEGER     NOT NULL DEFAULT 0,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_school_co_scholastic_activity_name CHECK (length(btrim(name)) > 0)
);
CREATE UNIQUE INDEX uq_school_co_scholastic_activity_school_name
    ON school_co_scholastic_activity (school_id, lower(btrim(name)));
CREATE INDEX idx_school_co_scholastic_activity_school ON school_co_scholastic_activity (school_id);

-- ── Remarks per card and student ───────────────────────────────────────────────────────────
CREATE TABLE report_card_remark_v2 (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id            BIGINT      NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    setup_id             BIGINT      NOT NULL REFERENCES report_card_setup(id) ON DELETE RESTRICT,
    student_id           VARCHAR(50) NOT NULL,
    teacher_remark       TEXT,
    teacher_updated_by   VARCHAR(255),
    teacher_updated_at   TIMESTAMP WITHOUT TIME ZONE,
    principal_remark     TEXT,
    principal_updated_by VARCHAR(255),
    principal_updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision             BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_report_card_remark_v2_setup_student UNIQUE (setup_id, student_id)
);
CREATE INDEX idx_report_card_remark_v2_school_student ON report_card_remark_v2 (school_id, student_id);

-- ── Co-scholastic grade per card, student and activity ─────────────────────────────────────
CREATE TABLE report_card_co_scholastic_v2 (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT      NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    setup_id    BIGINT      NOT NULL REFERENCES report_card_setup(id) ON DELETE RESTRICT,
    student_id  VARCHAR(50) NOT NULL,
    activity_id BIGINT      NOT NULL REFERENCES school_co_scholastic_activity(id) ON DELETE RESTRICT,
    grade       VARCHAR(5)  NOT NULL,
    updated_by  VARCHAR(255),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_report_card_co_scholastic_v2_setup_student_activity UNIQUE (setup_id, student_id, activity_id)
);
CREATE INDEX idx_report_card_co_scholastic_v2_setup ON report_card_co_scholastic_v2 (setup_id);
CREATE INDEX idx_report_card_co_scholastic_v2_school_student ON report_card_co_scholastic_v2 (school_id, student_id);
