-- Report Card V2, Phase 2: publications and frozen report-card documents. A publication is one
-- version of a setup for a class (or one section); each document is one student's frozen card in
-- that version — the snapshot of everything printed, the stored PDF and its own verification
-- token. Purely additive: the Phase 0 report_card_publication table, its template publications
-- and its verification tokens are untouched and keep verifying exactly as before.

CREATE TABLE report_card_publication_v2 (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         BIGINT       NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    setup_id          BIGINT       NOT NULL REFERENCES report_card_setup(id) ON DELETE RESTRICT,
    section_id        BIGINT       REFERENCES section(id) ON DELETE RESTRICT,   -- NULL = the whole class
    version           INTEGER      NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    document_count    INTEGER      NOT NULL DEFAULT 0,
    published_by      VARCHAR(255),
    published_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    withdrawn_by      VARCHAR(255),
    withdrawn_at      TIMESTAMP WITHOUT TIME ZONE,
    withdrawal_reason VARCHAR(500),
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_report_card_publication_v2_status CHECK (status IN ('ACTIVE', 'SUPERSEDED', 'WITHDRAWN')),
    CONSTRAINT ck_report_card_publication_v2_version CHECK (version > 0)
);
-- One ACTIVE publication per setup + scope (class or section); versions count up per scope.
CREATE UNIQUE INDEX uq_report_card_publication_v2_active_scope
    ON report_card_publication_v2 (setup_id, COALESCE(section_id, 0)) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX uq_report_card_publication_v2_scope_version
    ON report_card_publication_v2 (setup_id, COALESCE(section_id, 0), version);
CREATE INDEX idx_report_card_publication_v2_school_setup
    ON report_card_publication_v2 (school_id, setup_id, status);

CREATE TABLE report_card_document (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id          BIGINT       NOT NULL REFERENCES school(id) ON DELETE RESTRICT,
    publication_id     BIGINT       NOT NULL REFERENCES report_card_publication_v2(id) ON DELETE RESTRICT,
    setup_id           BIGINT       NOT NULL REFERENCES report_card_setup(id) ON DELETE RESTRICT,
    student_id         VARCHAR(50)  NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    version            INTEGER      NOT NULL,
    verification_token VARCHAR(64)  NOT NULL,
    reference          VARCHAR(20)  NOT NULL,
    -- Frozen identity shown on the card and on the public verification page.
    school_name        VARCHAR(255) NOT NULL,
    title              VARCHAR(150) NOT NULL,
    session_label      VARCHAR(20)  NOT NULL,
    class_name         VARCHAR(100) NOT NULL,
    section_name       VARCHAR(50),
    student_name       VARCHAR(255) NOT NULL,
    -- The frozen card: exactly what the stored PDF was rendered from.
    snapshot           JSONB        NOT NULL,
    snapshot_sha256    VARCHAR(64)  NOT NULL,
    pdf_object_key     VARCHAR(512) NOT NULL,
    pdf_sha256         VARCHAR(64)  NOT NULL,
    pdf_size           BIGINT       NOT NULL,
    renderer_version   VARCHAR(60)  NOT NULL,
    rendered_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    issued_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_report_card_document_status CHECK (status IN ('ACTIVE', 'SUPERSEDED', 'WITHDRAWN')),
    CONSTRAINT uq_report_card_document_publication_student UNIQUE (publication_id, student_id),
    CONSTRAINT uq_report_card_document_token UNIQUE (verification_token),
    CONSTRAINT uq_report_card_document_reference UNIQUE (reference)
);
CREATE INDEX idx_report_card_document_school_student ON report_card_document (school_id, student_id, status);
CREATE INDEX idx_report_card_document_setup_student ON report_card_document (setup_id, student_id, status);
CREATE INDEX idx_report_card_document_publication ON report_card_document (publication_id);
