-- Student Promotion / Session Rollover, Phase 1: one audit/reporting row per executed year-end
-- batch. Purely additive: individual decisions still go through the existing per-student
-- year-end and exit logic, and student_enrollment is unchanged.

CREATE TABLE student_rollover_run (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id             BIGINT       NOT NULL,
    source_session_id     BIGINT       NOT NULL,
    target_session_id     BIGINT       NOT NULL,
    class_id              BIGINT,                      -- NULL = the whole school
    started_by            VARCHAR(255) NOT NULL,
    started_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    finished_at           TIMESTAMP WITHOUT TIME ZONE,
    status                VARCHAR(30)  NOT NULL,
    total_students        INTEGER      NOT NULL DEFAULT 0,
    promoted_count        INTEGER      NOT NULL DEFAULT 0,
    detained_count        INTEGER      NOT NULL DEFAULT 0,
    pass_out_count        INTEGER      NOT NULL DEFAULT 0,
    transfer_count        INTEGER      NOT NULL DEFAULT 0,
    withdraw_count        INTEGER      NOT NULL DEFAULT 0,
    pending_count         INTEGER      NOT NULL DEFAULT 0,
    already_applied_count INTEGER      NOT NULL DEFAULT 0,
    failed_count          INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT ck_student_rollover_run_status
        CHECK (status IN ('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED')),
    CONSTRAINT ck_student_rollover_run_sessions_differ CHECK (source_session_id <> target_session_id),
    CONSTRAINT ck_student_rollover_run_counts CHECK (
        total_students >= 0 AND promoted_count >= 0 AND detained_count >= 0 AND pass_out_count >= 0
        AND transfer_count >= 0 AND withdraw_count >= 0 AND pending_count >= 0
        AND already_applied_count >= 0 AND failed_count >= 0),

    -- Tenant-safe: the sessions and class must belong to the run's school.
    CONSTRAINT fk_student_rollover_run_school FOREIGN KEY (school_id)
        REFERENCES school (id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_rollover_run_source FOREIGN KEY (school_id, source_session_id)
        REFERENCES academic_session (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_rollover_run_target FOREIGN KEY (school_id, target_session_id)
        REFERENCES academic_session (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_rollover_run_class FOREIGN KEY (school_id, class_id)
        REFERENCES school_class (school_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_student_rollover_run_school_sessions
    ON student_rollover_run (school_id, source_session_id, target_session_id, started_at DESC);
